using Burmalda.Core;
using UnityEngine;

namespace Burmalda.DebugVisuals
{
    /// <summary>
    /// Runtime references for the modular tomb kit. The asset is generated by
    /// TombEnvironmentIntegrationSetup, so no scene or prefab serialization is needed.
    /// </summary>
    public sealed class TombEnvironmentCatalog : ScriptableObject
    {
        public const string ResourcesPath = "Art/TombEnvironmentCatalog";

        [SerializeField] private Mesh _floorIntact;
        [SerializeField] private Mesh _floorWorn;
        [SerializeField] private Mesh _floorCracked;
        [SerializeField] private Mesh _wallStraight;
        [SerializeField] private Mesh _wallCorner;
        [SerializeField] private Material _sharedMaterial;

        private static TombEnvironmentCatalog _cached;
        private static bool _loadAttempted;

        public Mesh FloorIntact => _floorIntact;
        public Mesh FloorWorn => _floorWorn;
        public Mesh FloorCracked => _floorCracked;
        public Mesh WallStraight => _wallStraight;
        public Mesh WallCorner => _wallCorner;
        public Material SharedMaterial => _sharedMaterial;

        public static TombEnvironmentCatalog Load()
        {
            if (_loadAttempted) return _cached;
            _loadAttempted = true;
            _cached = Resources.Load<TombEnvironmentCatalog>(ResourcesPath);
            return _cached;
        }

        public Mesh ResolveFloor(GridCoordinate coordinate, bool isDestroyed)
        {
            if (isDestroyed && _floorCracked != null) return _floorCracked;

            // Stable spatial variation avoids a visible repeated pattern and does not
            // change between frames or consume the gameplay random stream.
            var hash = unchecked(coordinate.Row * 73856093 ^ coordinate.Column * 19349663);
            return (hash & 1) == 0 || _floorWorn == null ? _floorIntact : _floorWorn;
        }

#if UNITY_EDITOR
        public void EditorAssign(
            Mesh floorIntact,
            Mesh floorWorn,
            Mesh floorCracked,
            Mesh wallStraight,
            Mesh wallCorner,
            Material sharedMaterial)
        {
            _floorIntact = floorIntact;
            _floorWorn = floorWorn;
            _floorCracked = floorCracked;
            _wallStraight = wallStraight;
            _wallCorner = wallCorner;
            _sharedMaterial = sharedMaterial;
        }
#endif
    }
}
